---
- hosts: pod1_leafs
  connection: local
  gather_facts: no

  tasks:
  - name: Configure Arista Vlans
    eos_template:
      src: vlans.j2
      provider: "{{ eos_connection }}"

  - name: ConfigureArista Eth Interfaces
    eos_template:
      src: intf.j2
      provider: "{{ eos_connection }}"
